### PR TITLE
🧹 Handle slugs

### PR DESCRIPTION
**Pull request by laritakr**
# Story

Refs https://github.com/scientist-softserv/adventist-dl/issues/582

Removes `alternative_title` from forms
Removes `alternative_title` from bulkrax mappings

Additional Background:
In the adventist implementation of slugs, the predicate "alternative" is being used to store the slug. If viewing the data, the predicate will contain the slug if there is one, and otherwise it contains the uuid.

A second term and predicate was added for slugs, but remediation of prior data into the new predicate has not yet happened, which would be beyond the scope of current work as it would require a data migration.

With the hyrax upgrade, alternative_title is now included by default. By removing the alternative_title from the any create or edit ability, the data for slugs is still saved in the same location as alternative_title would be, but does not impede any behavior.

# Expected Behavior Before Changes

Work forms include `alternative_title`

# Expected Behavior After Changes

Work forms do not include `alternative_title`

# Screenshots / Video

<details>
<summary></summary>

**BEFORE, with and without a slug:**
Screenshot 2023-10-04 at 1 57 55 PM

Screenshot 2023-10-04 at 1 59 21 PM

</details>

# Notes

### CODE REVIEW

**Comment by laritakr** [comment]
todo: verify that updated specs work.

**Comment by ShanaLMoore** [comment]
Will this also solve the reason we can't delete works that have slugs? @laritakr

**Comment by laritakr** [comment]
> (prob not but asking anyways) - Will this also solve the reason we can't delete works that have slugs? @laritakr

Hmmm I don't know. I didn't realize we couldn't! Is there a ticket for that?

**Comment by ShanaLMoore** [comment]
https://github.com/scientist-softserv/adventist-dl/issues/567

**Review by jeremyf — APPROVED** [review]

**Pull request merged**
